DEBUG = True

ENABLE_WATCHDOG = True
WATCHDOG_TIMEOUT_MS = 30000

try:
	from local_settings import WIFI_PASSWORD
	from local_settings import WIFI_SSID
except ImportError:
	WIFI_SSID = "<fallback_ssid>"
	WIFI_PASSWORD = "<fallback_ssid_pwd>"

WIFI_RECONNECT_DELAY = 30
WIFI_MAX_RECONNECT_ATTEMPTS = 3
WIFI_CONNECT_TIMEOUT_S = 15
WIFI_RECONNECT_WAIT_S = 5

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 80
SERVER_ACCEPT_TIMEOUT_S = 1
SERVER_CLIENT_TIMEOUT_S = 2

GC_EVERY_N_REQUESTS = 10

SENSOR_SCL_PIN = 5
SENSOR_SDA_PIN = 4
SENSOR_READ_INTERVAL_MS = 5000
SENSOR_INIT_RETRY_MS = 2000
SENSOR_STALE_TOLERANCE_MS = 15000
SENSOR_HANG_TOLERANCE_MS = 12000
RESET_ON_SENSOR_HANG = False
